/*
DROP TABLE IF EXISTS Member;
create table Member(
                       memberId varchar(50),
                       password varchar(15),
                       memberName varchar(10),
                       email varchar(50),
                       regdate timestamp
);
DROP TABLE IF EXISTS BOARD;

create table BOARD(
       boardId int generated by default as identity,
       title varchar(20),
       content varchar(500),
       regDate timestamp,
       modDate timestamp,
       writer varchar(50)
);

 */